-- ============================================================
-- Auth: profiles, access_codes, employee_invites
-- Run in Supabase SQL Editor: https://supabase.com/dashboard/project/nantzwlhnphyirishxou/sql
-- ============================================================

-- 1. User profiles (extends auth.users)
create table if not exists profiles (
  id            uuid references auth.users on delete cascade primary key,
  role          text not null default 'owner' check (role in ('owner', 'employee')),
  full_name     text,
  franchise_id  uuid,
  created_at    timestamptz default now()
);

alter table profiles enable row level security;

create policy "Users can read their own profile"
  on profiles for select
  using (auth.uid() = id);

create policy "Users can update their own profile"
  on profiles for update
  using (auth.uid() = id);

-- 2. Owner access codes (generated by Franchisli admin after demos)
create table if not exists access_codes (
  id          uuid primary key default gen_random_uuid(),
  code        text unique not null,
  label       text,                          -- e.g. "Jane Smith - Golden Corral demo 2026-06-03"
  used        boolean default false,
  used_by     uuid references auth.users,
  used_at     timestamptz,
  created_at  timestamptz default now(),
  expires_at  timestamptz                    -- optional expiry
);

alter table access_codes enable row level security;
-- Only service role (admin client) can read/write codes

-- 3. Employee invites (sent by owners from their dashboard)
create table if not exists employee_invites (
  id           uuid primary key default gen_random_uuid(),
  email        text not null,
  full_name    text,
  franchise_id uuid,
  invited_by   uuid references auth.users,
  token        text unique not null default encode(gen_random_bytes(32), 'hex'),
  used         boolean default false,
  created_at   timestamptz default now(),
  expires_at   timestamptz default (now() + interval '7 days')
);

alter table employee_invites enable row level security;

create policy "Owners can view their own invites"
  on employee_invites for select
  using (auth.uid() = invited_by);

-- ============================================================
-- Seed: insert a first access code to test owner signup
-- Copy this code and use it on /signup/owner
-- ============================================================
insert into access_codes (code, label)
values ('FRNCH-DEMO1', 'First demo access code — delete after use')
on conflict (code) do nothing;
